# Generated by Django 5.1 on 2024-09-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_alter_room_options_room_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-updated', '-created')},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ('-date_of_joined',)},
        ),
        migrations.AlterModelOptions(
            name='messageitem',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('-updated', '-created')},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-date_of_joined',)},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='module',
            name='date_of_created',
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
